# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDefaultSuite():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1(self):
    self.driver.get("https://www.paruvendu.fr/")
    self.driver.set_window_size(1216, 776)
    self.driver.find_element(By.ID, "selectCategorie").click()
    self.driver.find_element(By.CSS_SELECTOR, "#chaines > li:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "#V li:nth-child(1)").click()
    self.driver.find_element(By.LINK_TEXT, "Déposer une annonce gratuite").click()
    self.driver.find_element(By.CSS_SELECTOR, ".field:nth-child(3) > .select").click()
    self.driver.find_element(By.CSS_SELECTOR, "#chaines > li:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "#V li:nth-child(1)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".rad-pro")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.ID, "descBien")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.ID, "descBien")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.ID, "descBien")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.ID, "descBien").click()
    self.driver.find_element(By.ID, "descBien").send_keys("je mets en vente ma voiture 207")
    self.driver.find_element(By.ID, "prix").click()
    self.driver.find_element(By.ID, "prix").send_keys("12 500")
    self.driver.find_element(By.ID, "ville").click()
    self.driver.find_element(By.ID, "codePostal").click()
    self.driver.find_element(By.ID, "codePostal").send_keys("75015")
  
